import streamlit as st
import pandas as pd
import plotly.express as px

from src.profiler import profile_dataframe
from src.column_suggester import suggest_column, get_selectbox_index
from src.metricpulse_llm_agent import run_metricpulse_llm_agent


st.set_page_config(
    page_title="MetricPulse LLM Agent",
    layout="wide"
)

st.title("MetricPulse LLM Agent")
st.caption("This page uses a real LLM planner to choose analytics tools. Python tools calculate the actual results.")

uploaded_file = st.file_uploader("Upload a CSV file", type=["csv"])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
else:
    df = pd.read_csv("data/sample_ecommerce.csv")
    st.info("Using sample ecommerce dataset. Upload your own CSV to test another dataset.")

profile = profile_dataframe(df)

st.write("### Dataset Preview")
st.dataframe(df.head())

date_columns = profile["date_like_columns"]
numeric_columns = profile["numeric_columns"]
categorical_columns = profile["categorical_columns"]

if not date_columns:
    st.error("No date-like column detected.")
    st.stop()

revenue_guess = suggest_column(
    numeric_columns,
    ["revenue", "sales", "amount", "total", "price", "order_value"]
)

order_guess = suggest_column(
    df.columns.tolist(),
    ["order_id", "order", "transaction_id", "transaction"]
)

segment_candidates = [
    col for col in categorical_columns
    if "id" not in col.lower()
]

if not segment_candidates:
    st.error("No useful segment column detected.")
    st.stop()

preferred_segment = suggest_column(
    segment_candidates,
    ["region", "category", "channel", "segment", "department"]
)

st.sidebar.header("LLM Agent Inputs")

date_col = st.sidebar.selectbox(
    "Date column",
    date_columns
)

kpi_name = st.sidebar.selectbox(
    "KPI",
    ["Revenue", "Orders", "Average Order Value"]
)

revenue_col = st.sidebar.selectbox(
    "Revenue column",
    numeric_columns,
    index=get_selectbox_index(numeric_columns, revenue_guess)
)

order_col = st.sidebar.selectbox(
    "Order ID column",
    df.columns.tolist(),
    index=get_selectbox_index(df.columns.tolist(), order_guess)
)

segment_col = st.sidebar.selectbox(
    "Segment column",
    segment_candidates,
    index=get_selectbox_index(segment_candidates, preferred_segment)
)

question = st.text_input(
    "Ask the MetricPulse LLM Agent",
    value="Why did revenue drop?"
)

run_agent = st.button("Run LLM Agent")

if run_agent:
    try:
        with st.spinner("LLM is planning tools and Python is running analysis..."):
            result = run_metricpulse_llm_agent(
                question=question,
                df=df,
                date_col=date_col,
                kpi_name=kpi_name,
                revenue_col=revenue_col,
                order_col=order_col,
                segment_col=segment_col
            )

        st.write("## LLM JSON Tool Plan")
        st.caption("This is the JSON plan generated by the LLM planner.")
        st.code(result["llm_plan_text"], language="json")

        st.write("## Tool Trace")
        st.caption("These are the tools that actually ran after validation.")
        st.dataframe(result["tool_trace"])

        if "generate_insight_summary" in result:
            st.write("## Answer")
            st.success(result["generate_insight_summary"])
        else:
            st.info("The LLM did not include generate_insight_summary in its plan.")

        if "calculate_kpi_trend" in result:
            st.write("## KPI Trend")
            trend_df = result["calculate_kpi_trend"]
            st.dataframe(trend_df)

            if not trend_df.empty:
                fig = px.line(
                    trend_df,
                    x="period",
                    y="kpi_value",
                    markers=True,
                    title=f"Monthly {kpi_name} Trend"
                )
                st.plotly_chart(fig, use_container_width=True)

        if "compare_periods" in result:
            st.write("## Period Comparison")
            st.json(result["compare_periods"])

        if "analyze_root_cause" in result:
            st.write("## Root-Cause Drivers")
            root_cause_df = result["analyze_root_cause"]
            st.dataframe(root_cause_df)

            if not root_cause_df.empty:
                fig = px.bar(
                    root_cause_df,
                    x="segment",
                    y="absolute_change",
                    title=f"{kpi_name} Change by {segment_col}"
                )
                st.plotly_chart(fig, use_container_width=True)

        if "detect_anomalies" in result:
            st.write("## Anomaly Detection")
            st.dataframe(result["detect_anomalies"])

        if "forecast_kpi" in result:
            st.write("## Forecast")
            st.dataframe(result["forecast_kpi"])

        if "run_sql_query" in result:
            st.write("## SQL Result")
            st.dataframe(result["run_sql_query"])

        with st.expander("Debug: LLM Prompt"):
            st.code(result["llm_prompt"], language="text")

    except Exception as error:
        st.error(f"LLM agent failed: {error}")
